chore: run shfmt

diff --git a/termv b/termv
--- a/termv
+++ b/termv
@@ -2,139 +2,138 @@
 
 VERSION=1.4
 BASH_BINARY="$(command -v bash)"
-TERMV_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/termv"
 TERMV_AUTO_UPDATE=${TERMV_AUTO_UPDATE:-true}
 TERMV_FULL_SCREEN=${TERMV_FULL_SCREEN:-false}
 
 TERMV_CHANNELS_URL=${TERMV_CHANNELS_URL:-"https://iptv-org.github.io/api/channels.json"}
 TERMV_STREAMS_URL=${TERMV_STREAMS_URL:-"https://iptv-org.github.io/api/streams.json"}
 
-FZF_VERSION=$(fzf --version | cut -d '.' -f 2- | cut -d ' ' -f 1 )
+FZF_VERSION=$(fzf --version | cut -d '.' -f 2- | cut -d ' ' -f 1)
 
 declare -x TERMV_SWALLOW=${TERMV_SWALLOW:-false}
 declare -x TERMV_MPV_FLAGS="${TERMV_DEFAULT_MPV_FLAGS:---no-resume-playback}"
 
+TERMV_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/termv"
 mkdir -p "${TERMV_CACHE_DIR:?}"
 
 has() {
-    case "$(command -v "$1" 2>/dev/null)" in
-        alias*|"") return 1
-    esac
+	case "$(command -v "$1" 2>/dev/null)" in
+	alias* | "") return 1 ;;
+	esac
 }
 
 _phi() {
-    >&2 printf '    %s\n' "$1"
+	printf >&2 '    %s\n' "$1"
 }
 
 _pht() {
-    >&2 printf '%s\n' "$@"
+	printf >&2 '%s\n' "$@"
 }
 
 # print error message & exit
 _pemx() {
-    >&2 printf '\033[31;1merror :\033[m %s\n' "$1"
-    exit 1
+	printf >&2 '\033[31;1merror :\033[m %s\n' "$1"
+	exit 1
 }
 
 version() {
-    _pht "$(basename "$0") $VERSION"
+	_pht "$(basename "$0") $VERSION"
 }
 
 usage() {
-    _pht "Usage:   $(basename "$0") [OPTIONS] query"
-    _pht
-    _pht "Options:"
-    _pht "  General Options:"
-    _phi "-h, --help                Print this help text and exit."
-    _phi "-v, --version             Print program version and exit."
-    _phi "-u, --update              Update channel list to latest version."
-    _pht
-    _pht "  Player Options:"
-    _phi "-f, --full-screen         Open mpv in fullscreen."
-    _phi "-s, --swallow             Swallow terminal during playback (X11 only) based on devour; https://github.com/salman-abedin/devour.sh"
-    _pht
-    _pht "  Environment variables:  "
-    _phi "TERMV_AUTO_UPDATE         Auto update channel list to latest version. (default: true)"
-    _phi "TERMV_SWALLOW             Always swallow terminal during playback. (default: false)"
-    _phi "TERMV_FULL_SCREEN         Always open mpv in fullscreen. (default: false)"
-    _phi "TERMV_DEFAULT_MPV_FLAGS   Default arguments which are passed to mpv. (default: --no-resume-playback)"
-    _phi "TERMV_CHANNELS_URL             URL to the channel list. (default: https://iptv-org.github.io/api/channels.json)"
-    _phi "                          Any other URL must be in the same format as the default one."
-    _phi "TERMV_STREAMS_URL             URL to the streams list. (default: https://iptv-org.github.io/api/streams.json)"
-    _phi "                          Any other URL must be in the same format as the default one."
-    _pht "  Improve me on GitHub:"
-    _phi "https://github.com/Roshan-R/termv"
+	_pht "Usage:   $(basename "$0") [OPTIONS] query"
+	_pht
+	_pht "Options:"
+	_pht "  General Options:"
+	_phi "-h, --help                Print this help text and exit."
+	_phi "-v, --version             Print program version and exit."
+	_phi "-u, --update              Update channel list to latest version."
+	_pht
+	_pht "  Player Options:"
+	_phi "-f, --full-screen         Open mpv in fullscreen."
+	_phi "-s, --swallow             Swallow terminal during playback (X11 only) based on devour; https://github.com/salman-abedin/devour.sh"
+	_pht
+	_pht "  Environment variables:  "
+	_phi "TERMV_AUTO_UPDATE         Auto update channel list to latest version. (default: true)"
+	_phi "TERMV_SWALLOW             Always swallow terminal during playback. (default: false)"
+	_phi "TERMV_FULL_SCREEN         Always open mpv in fullscreen. (default: false)"
+	_phi "TERMV_DEFAULT_MPV_FLAGS   Default arguments which are passed to mpv. (default: --no-resume-playback)"
+	_phi "TERMV_CHANNELS_URL             URL to the channel list. (default: https://iptv-org.github.io/api/channels.json)"
+	_phi "                          Any other URL must be in the same format as the default one."
+	_phi "TERMV_STREAMS_URL             URL to the streams list. (default: https://iptv-org.github.io/api/streams.json)"
+	_phi "                          Any other URL must be in the same format as the default one."
+	_pht "  Improve me on GitHub:"
+	_phi "https://github.com/Roshan-R/termv"
 }
 
 merge_json_files() {
-    jq 'unique_by (.channel) | map({id: .channel, url})' "${TERMV_CACHE_DIR:?}/streams_data.json" > "${TERMV_CACHE_DIR:?}/tmp_streams_data.json" 
-    jq 'map({id, name, categories, is_nsfw, languages, country})' "${TERMV_CACHE_DIR:?}/channels_data.json" > "${TERMV_CACHE_DIR:?}/tmp_channels_data.json"
-    jq -s 'add | group_by(.id) | map(add)' "${TERMV_CACHE_DIR:?}/tmp_streams_data.json" "${TERMV_CACHE_DIR:?}/tmp_channels_data.json" | jq 'map(select ( .url != null ))' >  "${TERMV_CACHE_DIR:?}/data.json" 
-    gawk 'NR<2 || NR>5' "${TERMV_CACHE_DIR:?}/data.json" > temp.json && mv temp.json "${TERMV_CACHE_DIR:?}/data.json"
-    rm "${TERMV_CACHE_DIR:?}/tmp_streams_data.json" 
-    rm "${TERMV_CACHE_DIR:?}/tmp_channels_data.json"
+	jq 'unique_by (.channel) | map({id: .channel, url})' "${TERMV_CACHE_DIR:?}/streams_data.json" >"${TERMV_CACHE_DIR:?}/tmp_streams_data.json"
+	jq 'map({id, name, categories, is_nsfw, languages, country})' "${TERMV_CACHE_DIR:?}/channels_data.json" >"${TERMV_CACHE_DIR:?}/tmp_channels_data.json"
+	jq -s 'add | group_by(.id) | map(add)' "${TERMV_CACHE_DIR:?}/tmp_streams_data.json" "${TERMV_CACHE_DIR:?}/tmp_channels_data.json" | jq 'map(select ( .url != null ))' >"${TERMV_CACHE_DIR:?}/data.json"
+	gawk 'NR<2 || NR>5' "${TERMV_CACHE_DIR:?}/data.json" >temp.json && mv temp.json "${TERMV_CACHE_DIR:?}/data.json"
+	rm "${TERMV_CACHE_DIR:?}/tmp_streams_data.json"
+	rm "${TERMV_CACHE_DIR:?}/tmp_channels_data.json"
 }
 
-update_jsonfiles(){
-    update_channelsfile
-    update_streamsfiles
-    merge_json_files
+update_jsonfiles() {
+	update_channelsfile
+	update_streamsfiles
+	merge_json_files
 }
 
 update_channelsfile() {
+	channelsEtagpath="${TERMV_CACHE_DIR:?}/channels_etag"
+	printf '%s' "Downloading ${TERMV_CHANNELS_URL:?}... "
+	[ -f "${channelsEtagpath:?}" ] && oldChannelsetag=$(<"${channelsEtagpath}") || oldChannelsetag="null"
 
-    channelsEtagpath="${TERMV_CACHE_DIR:?}/channels_etag"
-    printf '%s' "Downloading ${TERMV_CHANNELS_URL:?}... "
-    [ -f "${channelsEtagpath:?}" ] && oldChannelsetag=$(<"${channelsEtagpath}") || oldChannelsetag="null"
+	curl -s "${TERMV_CHANNELS_URL}" --etag-compare "${channelsEtagpath:?}" --etag-save "${channelsEtagpath:?}" -o "${TERMV_CACHE_DIR:?}/channels_data.json_new" \
+		-H "accept-encoding:gzip" --compressed && channelsDownloaded=1 || channelsDownloaded=0
 
-    curl -s "${TERMV_CHANNELS_URL}" --etag-compare "${channelsEtagpath:?}" --etag-save "${channelsEtagpath:?}" -o "${TERMV_CACHE_DIR:?}/channels_data.json_new" \
-    -H "accept-encoding:gzip" --compressed && channelsDownloaded=1 || channelsDownloaded=0
+	newChannelsetag=$(<"${channelsEtagpath}")
 
-    newChannelsetag=$(<"${channelsEtagpath}")
-
-    if [ ${channelsDownloaded} -eq 1 ] && [ "${newChannelsetag}" = "${oldChannelsetag}" ]; then
-        touch "${TERMV_CACHE_DIR:?}/channels_data.json" ;
-        printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
-    elif [ ${channelsDownloaded} -eq 1 ]; then
-      mv -f "${TERMV_CACHE_DIR:?}/channels_data.json_new" "${TERMV_CACHE_DIR:?}/channels_data.json"
-        printf '\033[32;1m %s \033[0m\n' "Done!" ;
-    elif [ ${channelsDownloaded} -eq 0 ]; then
-        rm -f "${channelsEtagpath:?}" "${TERMV_CACHE_DIR:?}/channels_data.json_new"
-        echo "${oldChannelsetag}" > "${channelsEtagpath}"
-        printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
-        exit 1
-    fi
+	if [ ${channelsDownloaded} -eq 1 ] && [ "${newChannelsetag}" = "${oldChannelsetag}" ]; then
+		touch "${TERMV_CACHE_DIR:?}/channels_data.json"
+		printf '\033[33;1m %s \033[0m\n' "Your version is already up to date."
+	elif [ ${channelsDownloaded} -eq 1 ]; then
+		mv -f "${TERMV_CACHE_DIR:?}/channels_data.json_new" "${TERMV_CACHE_DIR:?}/channels_data.json"
+		printf '\033[32;1m %s \033[0m\n' "Done!"
+	elif [ ${channelsDownloaded} -eq 0 ]; then
+		rm -f "${channelsEtagpath:?}" "${TERMV_CACHE_DIR:?}/channels_data.json_new"
+		echo "${oldChannelsetag}" >"${channelsEtagpath}"
+		printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
+		exit 1
+	fi
 }
 
 update_streamsfiles() {
 
-    streamsEtagpath="${TERMV_CACHE_DIR:?}/streams_etag"
-    printf '%s' "Downloading ${TERMV_STREAMS_URL:?}... "
-    [ -f "${streamsEtagpath:?}" ] && oldStreamsetag=$(<"${streamsEtagpath}") || oldStreamsetag="null"
+	streamsEtagpath="${TERMV_CACHE_DIR:?}/streams_etag"
+	printf '%s' "Downloading ${TERMV_STREAMS_URL:?}... "
+	[ -f "${streamsEtagpath:?}" ] && oldStreamsetag=$(<"${streamsEtagpath}") || oldStreamsetag="null"
 
-    curl -s "${TERMV_STREAMS_URL}" --etag-compare "${streamsEtagpath:?}" --etag-save "${streamsEtagpath:?}" -o "${TERMV_CACHE_DIR:?}/streams_data.json_new" \
-    -H "accept-encoding:gzip" --compressed && streamsDownloaded=1 || streamsDownloaded=0
+	curl -s "${TERMV_STREAMS_URL}" --etag-compare "${streamsEtagpath:?}" --etag-save "${streamsEtagpath:?}" -o "${TERMV_CACHE_DIR:?}/streams_data.json_new" \
+		-H "accept-encoding:gzip" --compressed && streamsDownloaded=1 || streamsDownloaded=0
 
-    newStreamsetag=$(<"${streamsEtagpath}")
+	newStreamsetag=$(<"${streamsEtagpath}")
 
-    if [ ${streamsDownloaded} -eq 1 ] && [ "${newStreamsetag}" = "${oldStreamsetag}" ]; then
-        touch "${TERMV_CACHE_DIR:?}/streams_data.json" ;
-        printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
-    elif [ ${streamsDownloaded} -eq 1 ]; then
-      mv -f "${TERMV_CACHE_DIR:?}/streams_data.json_new" "${TERMV_CACHE_DIR:?}/streams_data.json"
-        printf '\033[32;1m %s \033[0m\n' "Done!" ;
-    elif [ ${streamsDownloaded} -eq 0 ]; then
-        rm -f "${streamsEtagpath:?}" "${TERMV_CACHE_DIR:?}/streams_data.json_new"
-        echo "${oldStreamsetag}" > "${streamsEtagpath}"
-        printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
-        exit 1
-    fi
+	if [ ${streamsDownloaded} -eq 1 ] && [ "${newStreamsetag}" = "${oldStreamsetag}" ]; then
+		touch "${TERMV_CACHE_DIR:?}/streams_data.json"
+		printf '\033[33;1m %s \033[0m\n' "Your version is already up to date."
+	elif [ ${streamsDownloaded} -eq 1 ]; then
+		mv -f "${TERMV_CACHE_DIR:?}/streams_data.json_new" "${TERMV_CACHE_DIR:?}/streams_data.json"
+		printf '\033[32;1m %s \033[0m\n' "Done!"
+	elif [ ${streamsDownloaded} -eq 0 ]; then
+		rm -f "${streamsEtagpath:?}" "${TERMV_CACHE_DIR:?}/streams_data.json_new"
+		echo "${oldStreamsetag}" >"${streamsEtagpath}"
+		printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
+		exit 1
+	fi
 
 }
 
 # check if necessary programs are installed
 for prog in mpv fzf jq curl gawk bc; do
-     ! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, "
+	! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, "
 done
 
 [ -n "${dependencies_not_installed}" ] && _pemx "Missing dependencies, please install: ${dependencies_not_installed%??}."
@@ -164,16 +163,16 @@ done
 
 [ "${TERMV_FULL_SCREEN}" = true ] && TERMV_MPV_FLAGS="${TERMV_MPV_FLAGS} --fs"
 
-[[ -n "${TERMV_CATEGORY}" ]] && echo "Chosen category: $TERMV_CATEGORY" && TERMV_FILTER="$TERMV_FILTER | select(.categories[0].name == \"$TERMV_CATEGORY\")"
-[[ -n "${TERMV_LANGUAGE}" ]] && echo "Chosen language: $TERMV_LANGUAGE" && TERMV_FILTER="$TERMV_FILTER | select(.languages[0].name == \"$TERMV_LANGUAGE\")"
-[[ -n "${TERMV_COUNTRY}" ]] && echo "Chosen country: $TERMV_COUNTRY" && TERMV_FILTER="$TERMV_FILTER | select(.countries[0].name == \"$TERMV_COUNTRY\")"
+[[ -n ${TERMV_CATEGORY} ]] && echo "Chosen category: $TERMV_CATEGORY" && TERMV_FILTER="$TERMV_FILTER | select(.categories[0].name == \"$TERMV_CATEGORY\")"
+[[ -n ${TERMV_LANGUAGE} ]] && echo "Chosen language: $TERMV_LANGUAGE" && TERMV_FILTER="$TERMV_FILTER | select(.languages[0].name == \"$TERMV_LANGUAGE\")"
+[[ -n ${TERMV_COUNTRY} ]] && echo "Chosen country: $TERMV_COUNTRY" && TERMV_FILTER="$TERMV_FILTER | select(.countries[0].name == \"$TERMV_COUNTRY\")"
 
-[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/channels_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
-[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/streams_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles ; }
+[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/channels_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles; }
+[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/streams_data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_jsonfiles; }
 
-
-CHANNELS_LIST=$(jq -r ".[] $TERMV_FILTER | \"\(.name) \t \(.categories[]? // \"N/A\") \t \(.languages[]? // \"N/A\") \t \(.country? // \"N/A\") \t \(.url)\"" "${TERMV_CACHE_DIR:?}/data.json" |\
-                gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
+CHANNELS_LIST=$(
+	jq -r ".[] $TERMV_FILTER | \"\(.name) \t \(.categories[]? // \"N/A\") \t \(.languages[]? // \"N/A\") \t \(.country? // \"N/A\") \t \(.url)\"" "${TERMV_CACHE_DIR:?}/data.json" |
+		gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
                     {
                       name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
                       category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
@@ -181,43 +180,43 @@ CHANNELS_LIST=$(jq -r ".[] $TERMV_FILTER | \"\(.name) \t \(.categories[]? // \"N
                       countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
                       channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
                       print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
-                    }' | column -t -s $'\t' \
-                )
+                    }' | column -t -s $'\t'
+)
 
 _play() {
-    printf '%s\n' "Fetching channel, please wait..."
-    if [ "${TERMV_SWALLOW}" = true ]; then
-        WID=$(xdo id)
-        xdo hide
-        # shellcheck disable=SC2086
-        mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate
-        xdo show "$WID" && xdo activate "$WID"
-    else
-        # shellcheck disable=SC2086
-        mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}"
-    fi
+	printf '%s\n' "Fetching channel, please wait..."
+	if [ "${TERMV_SWALLOW}" = true ]; then
+		WID=$(xdo id)
+		xdo hide
+		# shellcheck disable=SC2086
+		mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate
+		xdo show "$WID" && xdo activate "$WID"
+	else
+		# shellcheck disable=SC2086
+		mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}"
+	fi
 }
 
 _playbg() {
-    { setsid -f mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate >/dev/null 2>&1 ; }
+	{ setsid -f mpv "${*##* }" "${TERMV_MPV_FLAGS}" --force-media-title="${*%%  *}" --force-window=immediate >/dev/null 2>&1; }
 }
 
 export -f _play
 export -f _playbg
 
-if [ $(echo "$FZF_VERSION < 25.0" | bc) == 1 ];then
-SHELL="${BASH_BINARY}" \
-            fzf -e -i --reverse --cycle --with-nth="1..-2"\
-                --bind "enter:execute(_play {})"\
-                --bind "double-click:execute(_play {})"\
-                --header="Select channel (press Escape to exit)" -q "${*:-}" \
-            < <( printf '%s\n' "${CHANNELS_LIST}" )
+if [ $(echo "$FZF_VERSION < 25.0" | bc) == 1 ]; then
+	SHELL="${BASH_BINARY}" \
+		fzf -e -i --reverse --cycle --with-nth="1..-2" \
+		--bind "enter:execute(_play {})" \
+		--bind "double-click:execute(_play {})" \
+		--header="Select channel (press Escape to exit)" -q "${*:-}" \
+		< <(printf '%s\n' "${CHANNELS_LIST}")
 else
-SHELL="${BASH_BINARY}" \
-            fzf -e -i --reverse --cycle --with-nth="1..-2"\
-                --bind "alt-]:execute-silent(_playbg {})"\
-                --bind "enter:execute(_play {})"\
-                --bind "double-click:execute(_play {})"\
-                --header="Select channel (press Escape to exit)" -q "${*:-}" \
-            < <( printf '%s\n' "${CHANNELS_LIST}" )
+	SHELL="${BASH_BINARY}" \
+		fzf -e -i --reverse --cycle --with-nth="1..-2" \
+		--bind "alt-]:execute-silent(_playbg {})" \
+		--bind "enter:execute(_play {})" \
+		--bind "double-click:execute(_play {})" \
+		--header="Select channel (press Escape to exit)" -q "${*:-}" \
+		< <(printf '%s\n' "${CHANNELS_LIST}")
 fi
